### PR TITLE
Fix Test and bug in MaturedBlocksProvider

### PR DESCRIPTION
**Pull request by fassadlr**

### CODE REVIEW

**Comment by quantumagi** [comment]
The `retrieveFromHeight` must be re-interpreted to be the maturity height. This means the various confirmation values (for each amount category) must be subtracted from this value to determine the heights at which to retrieve deposits. Similarly the `BlockHeight` being passed back must be the deposit height + confirmations. AFTER this change `maturedDeposit.BlockInfo.BlockHeight` can be renamed to `MaturityHeight`.

**Review by quantumagi — CHANGES_REQUESTED** [review]
Looking good so far.

The retrieveFromHeight (received from CCTS) must be re-interpreted to be the maturity height. This means the various confirmation values (for each amount category) must be subtracted from this value to determine the heights at which to retrieve deposits. Similarly the BlockHeight being passed back must contain the maturity height. ALL occurrences of maturedDeposit.BlockInfo.BlockHeight should be renamed to MaturityHeight - here and in CCTS. 
After this the BlockHeight can be re-introduced (with accompanying minor fix-ups) if it was being used for display purposes.

**Comment by fassadlr** [comment]
> The `retrieveFromHeight` (received from CCTS) must be re-interpreted to be the maturity height. This means that the various confirmation values (for each amount category) must be subtracted from this value to determine the heights at which to retrieve deposits. 

This makes sense but again, the way that I see it, this will result in CCTS advancing only 1 block at a time and as such syncing will take a very long time. We are now effectively only looking at one block at a time as the main chain's tip is now not considered in the calculation here: 

```
        private int? DetermineApplicableRetrievalHeight(DepositRetrievalType retrievalType, int retrieveFromHeight, out string message)
        {
            message = string.Empty;

            int applicableMaturityHeight;
            if (retrievalType == DepositRetrievalType.Small)
                applicableMaturityHeight = this.consensusTip.Height - this.federatedPegSettings.MinimumConfirmationsSmallDeposits;
            else if (retrievalType == DepositRetrievalType.Normal)
                applicableMaturityHeight = this.consensusTip.Height - this.federatedPegSettings.MinimumConfirmationsNormalDeposits;
            else if (retrievalType == DepositRetrievalType.Distribution)
                applicableMaturityHeight = this.consensusTip.Height - this.federatedPegSettings.MinimumConfirmationsDistributionDeposits;
            else
                applicableMaturityHeight = this.consensusTip.Height - this.federatedPegSettings.MinimumConfirmationsLargeDeposits;

```

See scenario below:

```
Pass Maturity Height 1 to MaturedBlockProvider:
	Min Confs for Small Deposits => 1 - 10 = -9 (not valid)
Pass 2:
	Min Confs for Small Deposits => 2 - 10 = -8 (not valid)
.
.
.
Pass 20:
	Min Confs for Small Deposits => 20 - 10 = 10 (valid) Deposits at block 10 = 0
Pass 21:
	Min Confs for Small Deposits => 21 - 10 = 11 (valid) Deposits at block 11 = 1
```

This will also require a small change to CCTS to advance the next maturity height every time we don't receive any deposits as we are now not relying on the main chain's tip to advance the next maturity height. These lines of code in CCTS wont work (or is applicable) if we are working with next maturity height:

```

                    if (maturedBlockDeposits.Count == 0 || maturedBlockDeposits.First().BlockInfo.BlockHeight != this.NextMatureDepositHeight)
                    {
                        this.logger.LogTrace("(-)[NO_VIABLE_BLOCKS]:true");
                        return new RecordLatestMatureDepositsResult().Succeeded();
                    }

                    if (maturedBlockDeposits.Last().BlockInfo.BlockHeight != this.NextMatureDepositHeight + maturedBlockDeposits.Count - 1)
                    {
                        this.logger.LogTrace("(-)[DUPLICATE_BLOCKS]:true");
                        return new RecordLatestMatureDepositsResult().Succeeded();
                    }

                    // Paying to our own multisig is a null operation and not supported.
                    bool depositFilter(IDeposit d) => d.TargetAddress != this.settings.MultiSigAddress.ToString();

                    if (!maturedBlockDeposits.Any(md => md.Deposits.Any(depositFilter)))
                    {
                        this.NextMatureDepositHeight += maturedBlockDeposits.Count;

                        this.logger.LogTrace("(-)[NO_DEPOSITS]:true");
                        return new RecordLatestMatureDepositsResult().Succeeded();
                    }
```

>Similarly the `BlockHeight` being passed back must contain the maturity height. ALL occurrences/references of/to `maturedDeposit.BlockInfo.BlockHeight` should then be _renamed_ to `MaturityHeight` - here and in CCTS.
> After this the `BlockHeight` can be re-introduced (with accompanying minor fix-ups) if it was being used for display purposes.

The `BlockHeight` property in the `BlockInfo` class cannot just be renamed to `MaturityHeight` because then to which maturity height does it refer to? Small deposits, normal deposits or large deposits? That block that you return can now contain small and large deposits.

**Comment by quantumagi** [comment]
> This makes sense but again, the way that I see it, this will result in CCTS advancing only 1 block at a time and as such syncing will take a very long time. 

The first maturity height that CCTS expects is block 1. At that point the chain could be at block 10,000. Now, even if CCTS expects block 1 (which obviously would contain nothing that was mature at that point) it does not stop you from presenting more blocks. Anything that became mature from block 1 onwards can be returned CCTS up to some pre-determined batch limit. Note that at each maturity height CCTS expects you to present a header with that `BlockHeight` plus the deposits that became mature. Following this scheme its clear that we will be presenting batches of blocks to CCTS until we reach height 10,000.

> The BlockHeight property in the BlockInfo class cannot just be renamed to MaturityHeight because then to which maturity height does it refer to? Small deposits, normal deposits or large deposits? That block that you return can now contain small and large deposits.

The height being refers to is the height at which the deposits became mature, be it small, normal or large deposits. So when you're returning a header for maturity height 200 you would include deposits created at block 200-N1, 200-N2 and 200-N3. Where N1, N2 and N3 correspond to the required confirmations for small, normal and large deposits respectively.

**Comment by fassadlr** [comment]
Replaced by #93

**Pull request closed without merging**
