### PR TITLE
[Cirrus] Don't create "add member" polls lacking voting requests

### PR DESCRIPTION
**Pull request by quantumagi**

### CODE REVIEW

**Comment by quantumagi** [comment]
Have reviewed the code but still pending unit testing.

**Comment by quantumagi** [comment]
Sync test complete with no pending member polls:

```
        >> Voting & Poll Data
        Polls Repository Height : 3502792 (Hash: eead0151eece187c9fcff7d478a8948af742e6fa9c7f0d5e0716086297400b6d)
        Blocks Processed        : 75491           Avg Time: 0.01 ms   Throughput: 974.83 per second

        Expired Member Polls    : 330             Expired Whitelist Polls       : 13
        Pending Member Polls    : 0               Pending Whitelist Polls       : 1
        Approved Member Polls   : 0               Approved Whitelist Polls      : 0
        Executed Member Polls   : 557             Executed Whitelist Polls      : 6
        Scheduled Votes         : 6               Scheduled votes will be added to the next block this node mines.
```

**Comment by quantumagi** [comment]
The tests will have to be modified to add a voting request.

**Comment by fassadlr** [comment]
@quantumagi as discussed please point to `release/1.1.3.0` :)

**Pull request closed without merging**
