### PR TITLE
Manually Submit Polls you haven't voted for

### PR DESCRIPTION
**Pull request by fassadlr**
There is currently a pending poll to add a member which isn't completing:

```"Action:'AddFederationMember',FederationMember:'PubKey:'03861718873ce9f80a125b6b2f3b090d0c927d3db98bf3a08869605866d0320b09',CollateralAmount:100000.00000000,CollateralMainchainAddress:XXkZKTXYYpdAEEmsXhpJXQ9raKNrMMyr6K'"```

This allows us to submit a vote for a pending poll where you havent voted on.

Also, I fixed the `JoinFederationRequestMonitor` scheduling votes in IBD.

### CODE REVIEW

**Comment by quantumagi** [comment]
The correct way to deal with the scheduling of votes is to treat it like a TODO list of what to add the next time one mines a block. Then, once the block is connected, the TODO list should be checked off. This way we don't have to rely on the somewhat fuzzy IBD flag logic.

**Review by quantumagi — CHANGES_REQUESTED** [review]
See comments.

**Comment by quantumagi** [comment]
I assume the situation we are remedying is where the node was stopped, the current tip contained a voting request, and there were some ScheduledVotes in-memory.

Instead of manually submitting polls we can have an API that takes a block height as parameter and passes the corresponding block to `JoinFederationRequestMonitor`.

Another way would be to include the voting request hash+height into the "add member" voting data. That way everything can be done automatically - i.e. instead of the user having to call an API. For the short-term/current issues one could simply scan the blocks preceding the poll start height to find the voting request.

**Comment by quantumagi** [comment]
BTW I'm not finding a pending poll for this member on Iain's VM. Is the poll even associated with a voting request???

**Comment by fassadlr** [comment]
Closing as been superceded by #227

**Pull request closed without merging**
