### PR TITLE
[Wallet] A rewind should also prompt the UI to get its balance and history again.

### PR DESCRIPTION
**Pull request by fassadlr**

### CODE REVIEW

**Review by zeptin — APPROVED** [review]

**Review by noescape00 — APPROVED** [review]
LGTM

**Comment by quantumagi** [comment]
The only improvement I can suggest is to set a flag and then do the signal outside of the transaction.

**Review by quantumagi — APPROVED** [review]
Looks great. Just the one possible enhancement.

**Comment by quantumagi** [comment]
Looks good.

**Pull request merged**
