### PR TITLE
Adjust minimum confirmations for CCTS transactions

### PR DESCRIPTION
**Pull request by fassadlr**

### CODE REVIEW

**Comment by quantumagi** [comment]
Just keep in mind that any confirmation reduction beneath the `MaxReorgLength` of the source chain runs the risk of creating "free money" on the target chain if the source chain is rewound after the spend to the target chain.

**Comment by fassadlr** [comment]
@quantumagi yes that is true but this will require a reorg of 50+ blocks on the source chain which we have never encountered.

@StratisIain can chime in here as he proposed these values.

**Comment by quantumagi** [comment]
It does introduce constraints on faster block times in the future, as that would go together with bigger reorgs. At that time we should remember to increase these values. Do we need an activation height for these changes?

**Comment by quantumagi** [comment]
The activation height will have to be compared against the height of the deposit transaction. Also it would require a 2 x BIP9, one for Cirrus and one for Strax - assuming the confirmations of both are being changed. The BIP9s may kick in at different heights.

I would suggest only changing it for Strax => Cirrus as the block production time is the longest for it. 
Maybe we can get @zeptin's opinion as well - he's usually pretty good with this kind of thing. My own viewpoint is that this is definitely a consensus thing as it should affect the validity of transactions being produced - e.g. there is a sense in which a CCTS can be found in a block "too early" due to the deposit not having "cleared" yet, right? Even if there is no such explicit check it would be difficult to untangle how this may implicitly be enforced, so best to assume such a rule exists (or could exist)- even if 
not now.

I am using BIP9/Activation height interchangeably. It can be either.

**Review by quantumagi — CHANGES_REQUESTED** [review]
See comments. Need more eyes on this.

**Comment by fassadlr** [comment]
Hi @quantumagi I'm busy doing the activation height work now 👍

**Comment by fassadlr** [comment]
Replaced by #974

**Pull request closed without merging**
