### PR TITLE
Resolve missing Key.GetHashCode override

### PR DESCRIPTION
**Pull request by quantumagi**
https://app.clickup.com/t/1qzu02x

### CODE REVIEW

**Comment by fassadlr** [comment]
@rowandh @quantumagi there is no way this would affect anything in the smart contract CLR?

**Comment by quantumagi** [comment]
@fassadlr , by fixing something, maybe, although I highly doubt it. Will let @rowandh make a call on this.

**Comment by fassadlr** [comment]
@quantumagi LOL I'm just super wary of any changes to the SC packages :P

**Comment by quantumagi** [comment]
@fassadlr , let me put this another way: The `GetHashCode` method has a fairly arbitrary implementation and it should be possible to change its results without affecting any other code - unless the code indirectly (or directly) using the method assumes a particular implementation. The SC code follows good programming practices so I doubt there would be issues. Maybe @rowandh can confirm.

**Comment by rowandh** [comment]
If the order of items in a dictionary somehow makes its way into what's being written to chain then it will cause problems. I don't think that's possible in this case as the entropy of the internals of the patricia tree shouldn't affect contract execution, so I think this is fine.

**Comment by fassadlr** [comment]
Thanks @rowandh. Gustav we will need to look at what references this project as we will need to make sure that update NUgets for it.

**Pull request merged**
