### PR TITLE
Local call logs

### PR DESCRIPTION
**Pull request by rowandh**
Fixes an issue where local calls would not return logs or internal transfers.

CC @mrtpain

### CODE REVIEW

**Review by YakupIpek — APPROVED** [review]
It looks good to me. Just some tests looks failed but it works on my local

**Comment by mrtpain** [comment]
Any chance we can get some more 👀 on this?

**Comment by rowandh** [comment]
@fassadlr anyone else you think should take a look?

**Comment by fassadlr** [comment]
@rowandh apologies! I forgot about this one. Can you do a tiny push to kick off the CI? Just wanna see the solution build and pass some tests.

**Review by fassadlr — APPROVED** [review]

**Pull request merged**
