### PR TITLE
Rocks DB

### PR DESCRIPTION
**Pull request by fassadlr**
The console changes has now been merged to this PR.

### CODE REVIEW

**Comment by fassadlr** [comment]
Guys, I'm gonna cleanup this PR by moving the console change out to another PR.

**Comment by quantumagi** [comment]
Could `IKeyValueStore` and `IKeyValueStoreTransaction` be supported as found in the DLT repo?

**Review by zeptin — APPROVED** [review]

**Comment by fassadlr** [comment]
> Could `IKeyValueStore` and `IKeyValueStoreTransaction` be supported as found in the DLT repo? That would give us more re-usability and enable us to run performance comparisons by swapping database implementations in/out. A lot of good work was done in DLT to make it really easy to add new database implementations - such as RocksDB, without having to re-visit each place databases are being used - i.e. update one file instead of 72.

We can for sure do this down the line. I just wanted to proof, very quickly and without refactoring the current architecture, that RocksDB works and doesn't give us those pesky crashes 👍

**Comment by quantumagi** [comment]
Man, I really don't know about this. This PR makes it virtually impossible to port the DLT work now as its going to make merging very, very difficult. If we ported that first you would only have needed to add one file for RocksDB. Anyway, that's my 2 cents for what its worth.

**Pull request merged**
