### PR TITLE
[Cirrus] Remove voting rule assumption

### PR DESCRIPTION
**Pull request by quantumagi**
Currently PR #836 is dependant on #833 as witnessed by the assumption noted in #836:

```
            // It is assumed that all scheduled and non-expired pending "add member" polls are valid and should be voted on.
            // We rely on checks elsewhere to ensure that no invalid "add member" polls (not having a valid voting request) are created.
```

Since these PRs will now be applied in different branches the above assumption needs to be removed. That's the purpose of this PR.

### CODE REVIEW

**Comment by fassadlr** [comment]
I assume we can close this one?

**Comment by quantumagi** [comment]
> I assume we can close this one?

Only if you revert #836 as well.

**Comment by fassadlr** [comment]
@quantumagi this PR was reverted from `1.1.2.0` before merged `1.1.2.0` into `1.2.0.0` 👍 

We can close this now and if need be, move to 1.2.1?

**Comment by quantumagi** [comment]
@fassadlr . I'm closing this now but as a result you will have to revert PR #836 as well.

**Pull request closed without merging**
