### PR TITLE
Resolve warnings found in Stratis.SmartContracts.IntegrationTests

### PR DESCRIPTION
**Pull request by quantumagi**
https://app.clickup.com/t/1qzu02x

### CODE REVIEW

**Comment by zeptin** [comment]
Perhaps @rowandh should comment about whether the modifications to the test contracts affect the validity of the tests in any way. They probably don't, but it is good to be sure.

**Comment by rowandh** [comment]
Both contracts appear to be unused, so we could just remove them.

**Comment by quantumagi** [comment]
Seems at least one of the contracts is being referenced by a test case:

image

**Comment by rowandh** [comment]
Ah, missed that one, better keep the test then. I'm not sure of the behaviour if using `new` so probably better just to rename the `Transfer` struct.

**Pull request merged**
